### ISSUE TITLE
Editor | Re-order Toolbox Questions

### ISSUE THREAD

**Issue by tucq88** [surveyjs/editor#257]
### Are you requesting a feature, reporting a bug or ask a question?
A feature

### What is the current behavior?
I want to re-order toolbox questions (mixed between copied and default ones), I saw attribute `orderedQuestions` in `QuestionToolbox` class but can't find any application of it. 
As `SurveyEditor.toolbox` is readonly, I can't override the default order as well. 

### What is the expected behavior?
`SurveyEditor.toolbox` should allow to re-order questions in custom order. Or I may not understand how to order it properly?

Please help

**Comment by dmitrykurmanov** [comment]
Thank you for your question.
We have a property in the doc : https://surveyjs.io/Documentation/Editor/?id=questiontoolbox#orderedQuestions. It can be used the following way: 
`editor.toolbox.orderedQuestions = ["checkbox", "text" ... ]`

Unfortunately, it doesn't work properly. We have fixed it right now. The fix will be available this evening.

**Comment by tucq88** [comment]
To me it still buggy 
```
this._overrideStrings(); 
this.editor = new SurveyEditor.SurveyEditor('surveyEditorContainer', editorOptions);    
this._hideItems();
this._addItems();
```
![result](https://i.gyazo.com/c42c99a668b412e8646f763116d0bf8c.png)


After apply new order, it overrides my previous override, and reset chages that I've made to toolbox items (Show hidden items,  Remove custom items - E.g Rating 5, Rating 7...) 
```
this._overrideStrings();
    this.editor = new SurveyEditor.SurveyEditor('surveyEditorContainer', editorOptions);
    this._hideItems();
    this._addItems();
    this.editor.toolbox.orderedQuestions = ['html', 'text', 'checkbox', 'radiogroup', 'dropdown', 'comment', 'rating', 'boolean'];
```
![result2](https://i.gyazo.com/5432c2302ce43074423b4593e1b1ea74.png)

Any suggestions ? 
My situation here is : 
- I hide some unused items and renamed some items
- I add custom items based on basic ones (Rating with fixed max/min, HTML with different labels..) 
- I want to order those items in a specific way
